In [3]:
import numpy as np

In [4]:
#random array permutation
a = np.arange(5)
print(a)
np.random.shuffle(a)
print(a)

[0 1 2 3 4]
[2 4 3 0 1]


In [5]:
l = [1,2,3,4,1,4,4]
x = np.array(l)

In [6]:
#unique elementts form numpy array with counts

In [7]:
unique, counts = np.unique(x, return_counts=True)

In [8]:
#take duplicats

In [9]:
duplicates = unique[counts>1]
duplicates

array([1, 4])

In [10]:
#check if element  is in array x 
#(elem can be a 1 value, list of values, array ...)
#(x also can be a list)

In [11]:
elem = [1,2]
np.isin(x,elem)

array([ True,  True, False, False,  True, False, False])

In [12]:
#first index of element

In [13]:
l.index(2)

1

In [14]:
#difference of the sets

In [15]:
set1 = set([1,2,3])
set2 = {1,4,5}
set1.difference(set2)

{2, 3}

In [16]:
# get random N element 

In [17]:
np.random.choice([1,2,3],2)

array([1, 2])

In [18]:
# some useful matrix operations

In [19]:
M = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [20]:
M.sum()

78

In [21]:
M.sum(axis=0)

array([22, 26, 30])

In [22]:
M.sum(axis=1)

array([ 6, 15, 24, 33])

In [23]:
M.mean(axis=0)

array([5.5, 6.5, 7.5])